### ISSUE TITLE
Metric mismatch with paper

### ISSUE THREAD

**Issue by ozmig77** [HanSolo9682/CounterCurate#4]
Hello nice work, thanks for the code and dataset release.

I have one question regard calculation of metric in position task.
In paper, the score is calculated as text-to-image manner:
![image](https://github.com/HanSolo9682/CounterCurate/assets/21963377/7a241481-ae8d-4b13-b438-a6b14b9edef0)
But in code, the score is calculated with image-to-text manner, S(C, I) > S(C', I) + S(C', I') > S(C, I')
https://github.com/HanSolo9682/CounterCurate/blob/main/benchmark/CLIP_test_position.py#L30
Can you clarify this?

 Thanks

**Comment by HanSolo9682** [comment]
Hi, thank you for your discovery! It seems like the paper did have a typo in how we conducted our experiments. It indeed should be the “image-to-text” manner you mentioned, which corresponds to our code, instead of what the paper currently describes. We will fix this in the next revised version of the paper.
